# Generated by Django 5.2.1 on 2025-05-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question_condition_operator_question_condition_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage"),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
    ]
