# Generated by Django 5.2.1 on 2025-05-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_survey_archived_at_survey_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='surveys.surveytheme', verbose_name='Thème'),
        ),
    ]
